server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.netflix.feign: DEBUG

spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    max-active: 2